###############################################################################
# Schuberg Philis
#
# Services Onboarding
#
# Please see readme.md for details
###############################################################################
#

#
#################################################################################################

trigger:
  branches:
    include:
    - "master"

variables:
  - name: vmImage
    value: 'windows-2019'
  - name: location
    value: 'West Europe'
  -group: onboarding-group

resources:
  repositories:
    - repository: sources
      type: git
      name: SBP Azure Circle/sbp-sources
      ref: refs/heads/master

stages:
  parameters:
    vmImage: '${{ variables.vmImage }}'

- stage: deploy
  displayName: deploy 
  jobs:
  - template: Pipelines/jobs/deployOnboarding.yml@sources
    parameters:
      connectedServiceName: "${{ format('{0}-spn', variables.username) }}"
      environmentName: 'tst001'
      location: '${{ variables.location }}'
      serviceGroup: '${{ variables.username }}'
      vmImage: '${{ variables.vmImage }}'
