trigger:
  branches:
    include:
    - "master"

variables:
  - name: vmImage
    value: 'windows-2019'
  - name: location
    value: 'West Europe'
  - group: onboarding-group

resources:
  repositories:
    - repository: sources
      type: git
      name: SBP Azure Circle/sbp-sources
      ref: refs/heads/master

stages:
  - stage: deploy
    displayName: deploy 
    jobs:
    - template: Pipelines/jobs/deployOnboarding.yml@sources
      parameters:
        connectedServiceName: $(username)-spn
        environmentName: 'tst001'
        location: '${{ variables.location }}'
        serviceGroup: "$(userName)"
        vmImage: '${{ variables.vmImage }}'
